Repository arrayfire/arrayfire-rust, pull requests merged in 2022-02, with the labels that each got.

#313 Fix clippy warnings
  .gitignore
  build.rs
  examples/helloworld.rs
  examples/neural_network.rs
  src/core/arith.rs
  src/core/array.rs
  src/core/index.rs
  src/core/macros.rs
  tests/error_handler.rs
Labels: Enhancement, Fix

#314 Report error for unsupported matching types in Match Template fn
  src/vision/mod.rs
Labels: Fix

#310 Error in build script when no backends are found
  .github/workflows/ci.yml
  build.rs
Labels: Enhancement, Build
